### ISSUE TITLE
Items in tree inherits parent color

### ISSUE THREAD

**Issue by JInfantesC** [massivelines/neutral-gray-ui#1]
Hello!

Items in tree-view are inheriting it's parent status making every object same colored, so is impossible to follow git status hints.

>![atom neutral-gray-ui issue-1](https://user-images.githubusercontent.com/7262829/31734078-d7dcdc16-b43d-11e7-9b68-2c1f6a338aa2.png)
>I created a new file and it turns green, just like the parent folder but screenshoot.jpg inherits the color of the folder when it should not

>![atom neutral-gray-ui issue-2](https://user-images.githubusercontent.com/7262829/31734420-eb285ed4-b43e-11e7-988f-00bae27f5b42.png)
>I've made changes to the file tree-view.less and styles folder turn yellow making every file yellow

Neutral-gray-ui 1.2.1
Atom 1.19.2 and 1.21

Thank you!
PD. Nice theme you have!

**Comment by massivelines** [comment]
I just pushed an update that fixes the color inheritance. 

I'm gonna link this to the atom-community ui-theme-template for an update on the starter theme.

If anything else looks wrong let me know.
Thanks

**Comment by JInfantesC** [comment]
Thank you, It works flawlessy!
